# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pepaloma <pepaloma@student.42urduliz.com>  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/05/09 20:18:43 by pepaloma          #+#    #+#              #
#    Updated: 2024/05/09 21:43:59 by pepaloma         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CXX = c++
CC = c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++98

megaphone : megaphone.o
